name: Update Dev-Collab Parent Repo

on:
  push:
    branches: [main]

jobs:
  sync-parent:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout backend repo
        uses: actions/checkout@v4

      - name: Sync parent repo
        env:
          TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git clone https://x-access-token:${TOKEN}@github.com/swarupcs/Dev-Collab.git parent
          cd parent

          git submodule update --remote --merge

          git add backend
          git commit -m "Auto-update backend submodule" || echo "No changes"
          git push
